use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Command {
    Insert(char),
    NewLine,
    Backspace,
    Delete,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    MoveHome,
    MoveEnd,
    PageUp,
    PageDown,
    Save,
    SaveAs(PathBuf),
    Quit,
    ConfirmQuit,
    Cancel,
    OpenHelp,
    OpenSearch,
    OpenGoto,
    OpenFileTree,
    NewFile,
    SearchNext,
    SearchPrev,
    UpdateSearch(String),
    CloseOverlay,
    SetLineColor(u8),
    ResetLineColor,
    GotoLine(usize),
    Noop,
}
